/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function Model({ ...props } : GroupProps) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d/Waifu/A_Cleric_IdleEquipped.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <skinnedMesh name="SK_Cleric" geometry={nodes.SK_Cleric.geometry} material={materials.M_Cleric_modular_master_2_Inst_SK_Cleric} skeleton={nodes.SK_Cleric.skeleton}>
          <primitive object={nodes.root} />
        </skinnedMesh>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/Waifu/A_Cleric_IdleEquipped.gltf')
