/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function Model({ ...props }: GroupProps) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3d/man/SK_Mannequin_UE4_WithWeapon.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon.geometry} material={materials.M_UE4Man_Body_Inst} skeleton={nodes.SK_Mannequin_UE4_WithWeapon.skeleton} />
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon_1.geometry} material={materials.M_UE4Man_ChestLogo} skeleton={nodes.SK_Mannequin_UE4_WithWeapon_1.skeleton} />
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon_2.geometry} material={materials.MaterialInstanceDynamic_0} skeleton={nodes.SK_Mannequin_UE4_WithWeapon_2.skeleton} />
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon_3.geometry} material={materials.MaterialInstanceDynamic_1} skeleton={nodes.SK_Mannequin_UE4_WithWeapon_3.skeleton} />
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon_4.geometry} material={materials.MaterialInstanceDynamic_2} skeleton={nodes.SK_Mannequin_UE4_WithWeapon_4.skeleton} />
      <skinnedMesh geometry={nodes.SK_Mannequin_UE4_WithWeapon_5.geometry} material={materials.MaterialInstanceDynamic_3} skeleton={nodes.SK_Mannequin_UE4_WithWeapon_5.skeleton} />
      <primitive object={nodes.root} />
    </group>
  )
}

useGLTF.preload('/3d/man/SK_Mannequin_UE4_WithWeapon.gltf')
